name: education_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  spincircle_bottom_bar: ^2.0.0
  like_button: ^2.0.5
  flutter_rating_bar: ^4.0.1
  video_player: ^2.8.7
  chewie: ^1.8.1
  image_picker: ^1.1.2
  file_picker: ^8.0.6




  # state management
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_gemini: ^2.0.4
  flutter_markdown: ^0.7.3
  google_generative_ai: ^0.4.3
  connectivity_plus: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/onBoarding/onboarding_1.png
    - assets/onBoarding/onboarding_2.png
    - assets/onBoarding/onboarding_3.png
    - assets/logo/logo-no-background.png
    - assets/logo/google-icon.png
    - assets/email_verifications/Verified-bro.png
    - assets/email_verifications/Emails-bro.png
    - assets/forget_password/Email campaign-rafiki.png
    - assets/user/user-image.png
    - assets/logo/1.mp4
    - assets/logo/2.mp4
    - assets/logo/3.mp4
    - assets/logo/4.mp4
    - assets/logo/5.mp4

    - assets/logo/math.png
    - assets/logo/english.png
    - assets/logo/1.png
    - assets/logo/2.png
    - assets/logo/3.png
    - assets/logo/4.png
    - assets/logo/5.png
    - assets/logo/post1.png
    - assets/logo/post2.png
    - assets/user/images.jpg
    - assets/logo/ai.png








  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

